backend: "OpenGL"
run_tests: True
msaa16: False
flush_after_render: True
vsync: False
flip_after_render: False
srgb: True
debug_text: True
debug_stats: True

startup_state: menus/ingame.yaml
# startup_state: menus/intro_animation.yaml
